### ISSUE TITLE
ReferenceError: global is not defined in runtime

### ISSUE THREAD

**Issue by smelnikov** [WalletConnect/walletconnect-monorepo#1658]
**Describe the bug**
Error when executing the example code

**SDK Version (if relevant)**
"@walletconnect/sign-client": "2.1.3",
"typescript": "^4.9.3",
"vite": "^3.2.4"

**To Reproduce**
Checkout branch `global-is-not-defined` of repo: https://github.com/smelnikov/walletconnect-sample
```sh
yarn install
npx vite
```
A runtime error appears:
```sh
Uncaught ReferenceError: global is not defined
    at localStorage.js:49:3
    at node_modules/localStorage/lib/localStorage.js (localStorage.js:54:1)
    at __require2 (@walletconnect_sign-client.js?v=a6844a88:18:50)
    at node_modules/@walletconnect/keyvaluestorage/dist/cjs/browser/index.js (index.ts:1:1)
    at __require2 (@walletconnect_sign-client.js?v=a6844a88:18:50)
    at index.js:1848:18
```

**Expected behavior**
There are no errors in runtime.

**Comment by bkrem** [comment]
Thanks for raising this and especially including a repro for it @smelnikov 💯 

While https://github.com/WalletConnect/walletconnect-utils/pull/36 will fix this type of issue for the code we (WalletConnect) own, this seems to be a reference in the `localStorage` dependency. 

Did some digging and found the `global` reference here:
https://git.coolaj86.com/coolaj86/local-storage.js/src/branch/local-storage/lib/localStorage.js#L49

cc @ganchoradkov, not sure what the best move here is, but I suspect we either:
- Submit a patch to the localStorage lib (who knows if/when that gets merged)
- Fork it and patch ourselves so we own the code.
- Use a different localStorage lib (seems drastic for an env/global reference issue but maybe wise long term)

**Comment by bkrem** [comment]
For anyone bumping into this I'd suggest using the one-liner monkey-patch [suggested here](https://github.com/WalletConnect/walletconnect-monorepo/issues/1299#issuecomment-1311368877) in envs that don't support `global` until this is fully resolved:
```
window.global ||= window
```

----

Alternatively, this can be handled via bundler config (e.g. in `vite.config.js`) as shown by @smelnikov here: https://github.com/smelnikov/walletconnect-sample/commit/a4e658ee2b6cfaa6b5de5447dacc54eff342267f

**Comment by smelnikov** [comment]
@bkrem 
I solved this problem with [define](https://vitejs.dev/config/shared-options.html#define) `global` variable during build https://github.com/smelnikov/walletconnect-sample/commit/a4e658ee2b6cfaa6b5de5447dacc54eff342267f

But it looks like this must be fixed at the top level of the library.

**Comment by bkrem** [comment]
Fixed in https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/2.1.4

There shouldn't be any more unhandled `global` references in our source or dependencies now.

Thanks again for the minimal reproduction here 🙏 

Please let us know if this is still reproducible and we'll reopen.

**Comment by smelnikov** [comment]
Thank you, now this error does not occur.

**Comment by ionvv** [comment]
> There shouldn't be any more unhandled `global` references in our source or dependencies now.
> 
> Thanks again for the minimal reproduction here 🙏
> 
> Please let us know if this is still reproducible and we'll reopen.

@smelnikov - your solution works, thanks!

@bkrem Seems that for vite + vue it's still not fixed. I'm using [erdjs's provider](https://github.com/ElrondNetwork/elrond-sdk-erdjs-wallet-connect-provider/compare/v2.1.0-beta.4...v2.1.0-beta.5) which is using @walletconnect/sign-client:2.1.4

**Comment by bkrem** [comment]
Ok thanks for reporting @ionvv. When I checked with the repro provided here all was fine. I'm also not aware of any other `global` references both in our source or dependencies (could have missed something in the deps though).

Could you provide a minimal reproduction of what you're seeing in your setup or at a minimum the stack trace pointing to the rogue `global` reference please? If reproducible I will of course reopen this until fixed 👍
