### ISSUE TITLE
Jest error related to uint8arrays and multiformats dependencies after migration to 2.1.4

### ISSUE THREAD

**Issue by alexeygorbachevsky** [WalletConnect/walletconnect-monorepo#1749]
![image](https://user-images.githubusercontent.com/37103509/207011751-aa2d2cc7-8b9b-4f93-96aa-91f7ecf47c5f.png)

**Comment by alexeygorbachevsky** [comment]
I have fixed it via solution that was suggested here **_https://github.com/achingbrain/uint8arrays/issues/21_**. 
Read the link pls and make relevant fixes or add note about this to migration doc.

**Comment by ganchoradkov** [comment]
hey @alexeygorbachevskiy thanks for the report.

Could you provide steps to reproduce?

**Comment by alexeygorbachevsky** [comment]
@ganchoradkov 
The minimum steps to reproduce are next (if import is commented, the test will be passed):
![image](https://user-images.githubusercontent.com/37103509/207537063-81b5cff0-21f6-4a7e-9440-402c3acd3523.png)

**Comment by carlosrsabreu** [comment]
I'm getting the same error also. Not sure but adding an ESM file in the `dist` and `module` field in `package.json` could help.

**Comment by nicolasbrugneaux** [comment]
This error is still happening by the way. I used the [previously mentioned](https://github.com/WalletConnect/walletconnect-monorepo/issues/1749#issuecomment-1346205582) solution, but this wasn't intuitive at all. It seems that projects using jest and migrating to WCv2 could all be concerned.

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)

**Comment by devon-bfs** [comment]
I received the same issue 

Adding a babel.config.js file with

`module.exports = {
	presets: [
		'@babel/preset-react',
		[
			'@babel/preset-env',
			{
				targets: {
					node: 'current',
				},
			},
		],
	],
};`

Solved if for me.

Gave me another issue though `TextEncoder not defined`

**Comment by nghongphuong94** [comment]
Hi @devon-bfs, I also got `TextEncoder not defined`. Did you resolve it?

**Comment by glitch-txs** [comment]
@nghongphuong94 you probably need a polyfill, maybe try something like https://github.com/anonyco/FastestSmallestTextEncoderDecoder
