### ISSUE TITLE
Module parse failed: @walletconnect/ethereum-provider

### ISSUE THREAD

**Issue by ColligenceLabs** [WalletConnect/walletconnect-monorepo#1973]
node : v16.19.0
react : 17.0.2

      ./node_modules/@walletconnect/ethereum-provider/dist/index.es.js 49:24
      Module parse failed: Unexpected token (49:24)
      File was processed with these loaders:
       * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
      You may need an additional loader to handle the result of these loaders.
      |           }
      |         },
      >       pairingTopic: t?.pairingTopic
      |       });
      |       if (!s) return;

**Comment by ColligenceLabs** [comment]
same issues are in @walletconnect/utils ...

      ./node_modules/@walletconnect/utils/dist/index.es.js 114:17
      Module parse failed: Unexpected token (114:17)
      File was processed with these loaders:
       * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
      You may need an additional loader to handle the result of these loaders.
      |   return e.includes(":") ? [e] : n.chains || [];
      | }
      > const R = e => e?.split(":"),
      |   ae = e => {
      |     const n = e && R(e);

**Comment by ColligenceLabs** [comment]
I don't like ejecting webpack from my React projects but in this case I have to.

After ejecting then add 2 babel plugins into my webpack.config.js

      plugins: [
         '@babel/plugin-proposal-nullish-coalescing-operator',
         '@babel/plugin-proposal-optional-chaining',
      ],

**Comment by hwnahm** [comment]
But I am not prefer ejecting webpack from my react project.

**Comment by jeremy-kunzhou** [comment]
I am facing the same problem with expo-web.
```
const createExpoWebpackConfigAsync = require("@expo/webpack-config")

// Expo CLI will await this method so you can optionally return a promise.
module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(env, argv)
  // If you want to add a new alias to the config.
  // config.resolve.alias["moduleA"] = "moduleB"
  config.resolve.alias['react-native-maps'] = 'react-native-web-maps';

  // Maybe you want to turn off compression in dev mode.
  if (config.mode === "development") {
    config.devServer.compress = false
  }

  // Or prevent minimizing the bundle when you build.
  // if (config.mode === "production") {
  //   config.optimization.minimize = false
  // }

  // Finally return the new config for the CLI to use.
  return config
}

```

How can i add the new babel plugin into this config.
Many Thanks.

**Comment by outlawcode** [comment]
> I don't like ejecting webpack from my React projects but in this case I have to.
> 
> After ejecting then add 2 babel plugins into my webpack.config.js
> 
> ```
>   plugins: [
>      '@babel/plugin-proposal-nullish-coalescing-operator',
>      '@babel/plugin-proposal-optional-chaining',
>   ],
> ```

Can you show me how  did you resolved it? meaning ejecting webpack

**Comment by jeremy-kunzhou** [comment]
> I am facing the same problem with expo-web.
> 
> ```
> const createExpoWebpackConfigAsync = require("@expo/webpack-config")
> 
> // Expo CLI will await this method so you can optionally return a promise.
> module.exports = async function (env, argv) {
>   const config = await createExpoWebpackConfigAsync(env, argv)
>   // If you want to add a new alias to the config.
>   // config.resolve.alias["moduleA"] = "moduleB"
>   config.resolve.alias['react-native-maps'] = 'react-native-web-maps';
> 
>   // Maybe you want to turn off compression in dev mode.
>   if (config.mode === "development") {
>     config.devServer.compress = false
>   }
> 
>   // Or prevent minimizing the bundle when you build.
>   // if (config.mode === "production") {
>   //   config.optimization.minimize = false
>   // }
> 
>   // Finally return the new config for the CLI to use.
>   return config
> }
> ```
> 
> How can i add the new babel plugin into this config. Many Thanks.

I fixed this problem by upgrading @expo/webpack-config to @18.1.0.
The plugin uses webpack 5. In my pervious version of webpack-config@0.17.4, the version of webpack is 4
I didn't try to dig more about the default plugins used with this webpack.
Just mention it and hope it helps.

**Comment by jonomnom** [comment]
I had the same issue, I had to convert all of the erroring files into be compiled with babel.
Here is my webpack.config.js
```
rules: [
      {
        test: /\.tsx?$/,
        loader: 'esbuild-loader',
        exclude: /node_modules/,
        options: {
          loader: 'tsx',
          target: 'es2018',
        },
      },
      {
        test: /ethereum-provider\/dist\/index\.es\.js/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env'],
          },
        },
      },
      {
        test: /\@walletconnect\/.*\/index\.es\.js/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env'],
          },
        },
      },
      {
        test: /ethereum-provider\/dist\/index\.es\.js/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env'],
          },
        },
      },
      // {
      //   test: /\@walletconnect\/.*\/index.js/,
      //   use: {
      //     loader: 'babel-loader',
      //     options: {
      //       presets: ['@babel/preset-env'],
      //     },
      //   },
      // },
       {
        test: /\@walletconnect\/modal-ui\/dist\/index\.js/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env'],
          },
        },
      },
       {
        test: /\@walletconnect\/modal-core\/dist\/index\.js/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env'],
          },
        },
      },
      {
        test: /\.(png|svg|jpg|gif|woff|woff2|eot|ttf|otf|ico)$/,
        use: ['file-loader'],
      },
    ]
    ```

**Comment by outlawcode** [comment]
> 

Still got same error.
I have spent almost 3days for this issues :(

**Comment by yuanxxxxxx** [comment]
> > 
> 
> Still got same error. I have spent almost 3days for this issues :(

Hi bro, is this problem solved? I spent a long time and still not solved.

**Comment by xdefidev** [comment]
anyone found solution?
