### ISSUE TITLE
@walletconnect/sign-client: init function throws "TypeError: undefined is not a function"

### ISSUE THREAD

**Issue by nop33** [WalletConnect/walletconnect-monorepo#4296]
**Describe the bug**
At [Alephium](https://github.com/alephium) we have been using `@walletconnect/sign-client` for a while now. Our users suddenly started reporting that they cannot connect to WalletConnect via our apps. We noticed through our analytics that the `SignClient.init` method call is throwing this error:

```
TypeError: undefined is not a function
```

This is how we call the `init` method: https://github.com/alephium/alephium-frontend/blob/fix-wallet-connect-again/apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx#L155-L166

We have not managed to reproduce this error in a development environment so we don't have any further logs.

**SDK Version (if relevant)**
 - Client: JS
 - Version 2.11.2

**To Reproduce**
-

**Expected behavior**
The client to get initialized

**Screenshots**
-

**Smartphone (please complete the following information):**
 - Device: Google Pixel 2 XL
 - OS: Android

**Additional context**
-

**Comment by ganchoradkov** [comment]
Hey @nop33 thanks for the report. Did this issue started after recent update? Trying to narrow down potential culprit.
>TypeError: undefined is not a function

Is this log confirmed to be thrown by Sign Client?
We've seen similar errors on react-native caused by broken linking that were resolved via fresh install/build of the project after dependency update

**Comment by nop33** [comment]
Thank you @ganchoradkov for your prompt message.

> Did this issue started after recent update?

We have not updated our deps recently, no.

> Is this log confirmed to be thrown by Sign Client?

Yes, confirmed. I am wrapping the `SignClient.init` call with a try/catch and I confirm that the `catch` is triggered: https://github.com/alephium/alephium-frontend/blob/fix-wallet-connect-again/apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx#L158-L176

> We've seen similar errors on react-native caused by broken linking that were resolved via fresh install/build of the project after dependency update

Hm, what do you mean by "fresh install"? What is troubling me is that some users (including myself) do not face this issue, whereas some others do. This issue started happening to current installations, we haven't released an updated version of our app in the meantime. I've tried releasing a newer testing version of the app (so, new build) and sent it to some of our users who are helping us debug. They still have the problem and I don't.

**Comment by nop33** [comment]
I've uninstallad all walletconnect deps and installed them again, build a new version, but users still get the exception at the `.init` call.

**Comment by diomark** [comment]
This is causing a lot of headaches for some of the walletconnect users:(

**Comment by bkrem** [comment]
cc @ignaciosantise for possible ways to resolve 🙏  Seems to be RN-related, also looking at the linked repo's dependencies, `react-native-compat` is in use.

**Comment by nop33** [comment]
The problem was solved after clearing all WalletConnect data: https://github.com/alephium/alephium-frontend/blob/fix-wallet-connect-again/apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx#L967-L1004
